language: ruby
cache: bundler

rvm:
  - jruby
  - 2.1.1

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - brentkastner@gmail.com
    on_failure: change
    on_success: never