language: ruby
cache: bundler

rvm:
  - 2.1.1
  - 2.1.0
  - 2.0.0

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - brentkastner@gmail.com
    on_failure: change
    on_success: never